filter:
    excluded_paths:
        - Resources/public
        - src/Tests/*
        - vendor

tools:
    external_code_coverage:
        timeout: 1200
    php_code_sniffer:
        config:
            standard: PSR2
    php_cpd:
        excluded_dirs:
            - Resources/public
            - vendor
    php_cs_fixer:
        config:
            level: all
    php_hhvm: true
    php_loc:
        excluded_dirs:
            - Resources/public
            - vendor
    php_mess_detector: true
    php_pdepend:
        excluded_dirs:
            - Resources/public
            - vendor
    php_analyzer: true
    sensiolabs_security_checker: true